spring:
  application:
    name: isi
  datasource:
    url: jdbc:mysql://localhost:3306/isi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zpg1314521@
    driver-class-name: com.mysql.cj.jdbc.Driver

